name: Telegram Notion Bot

on:
  schedule:
    - cron: '*/45 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python bot.py

      - name: Save offset
        run: |
          git config user.name "peter-eshak-abdo"
          git config user.email "petereshak11@gmail.com"
          git add last_offset.txt
          git diff --staged --quiet || git commit -m "update offset"
          git push
